version: '3.3'

services:

    filezilla:
        image: kasmweb/filezilla:1.13.1
        container_name: filezilla
        ports:
            - "6901:6901"
        environment:
            - VNC_PW=p4ssw0rd
        shm_size: '512m'  
        restart: unless-stopped 

        
